apiVersion: v1
kind: PersistentVolume
metadata:
  name: tile-storage-pv
  labels:
    app.kubernetes.io/name: tile-storage
    app.kubernetes.io/component: tiler
    app.kubernetes.io/part-of: maps-platform
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/tiles
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tile-pvc
  labels:
    app.kubernetes.io/name: tile-storage
    app.kubernetes.io/component: tiler
    app.kubernetes.io/part-of: maps-platform
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Gi
