/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { ThreeElements } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import { BufferGeometry, Mesh, NormalBufferAttributes } from 'three';
import { materialBorderGen } from '../utils/color';

type TardisModelProps = ThreeElements['group'];

// Helper to get geometry from a node and cast to the expected type for materialBorderGen
const getGeometry = (node: Mesh): BufferGeometry<NormalBufferAttributes> =>
    node.geometry;

// Cast geometry to the type expected by materialBorderGen
// BufferGeometry has the required 'attributes.normal' property
const toMaterialGeom = (
    geom: BufferGeometry<NormalBufferAttributes>
): Parameters<typeof materialBorderGen>[0] =>
    geom as unknown as Parameters<typeof materialBorderGen>[0];

export function TardisModel(props: TardisModelProps) {
    const { nodes } = useGLTF(
        'https://s3.amazonaws.com/tardis.digital/TARDIS.glb'
    );
    console.log(nodes);
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={getGeometry(nodes.Roundcube001 as Mesh)}
                material={materialBorderGen(
                    toMaterialGeom(getGeometry(nodes.Roundcube001 as Mesh))
                )}
                position={[0, 2.7, 0]}
            />
            <group position={[0, 0.05, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={getGeometry(nodes.Base_1 as Mesh)}
                    material={materialBorderGen(
                        toMaterialGeom(getGeometry(nodes.Base_1 as Mesh))
                    )}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={getGeometry(nodes.Base_2 as Mesh)}
                    material={materialBorderGen(
                        toMaterialGeom(getGeometry(nodes.Base_2 as Mesh))
                    )}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={getGeometry(nodes.Pillar_Tops as Mesh)}
                    material={materialBorderGen(
                        toMaterialGeom(getGeometry(nodes.Pillar_Tops as Mesh))
                    )}
                    position={[-0.57, 2.35, 0.57]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={getGeometry(nodes.Window_Frame as Mesh)}
                    material={materialBorderGen(
                        toMaterialGeom(getGeometry(nodes.Window_Frame as Mesh))
                    )}
                    position={[0.53, 1.51, 0.24]}
                    rotation={[0, Math.PI / 2, 0]}
                >
                    <group
                        position={[0, 0.21, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.49, 1, 0.57]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(nodes.Window_Glass_1 as Mesh)}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Window_Glass_1 as Mesh)
                                )
                            )}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(nodes.Window_Glass_2 as Mesh)}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Window_Glass_2 as Mesh)
                                )
                            )}
                        />
                    </group>
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={getGeometry(nodes.Window_Frame003 as Mesh)}
                    material={materialBorderGen(
                        toMaterialGeom(
                            getGeometry(nodes.Window_Frame003 as Mesh)
                        )
                    )}
                    position={[0.53, 1.51, -0.24]}
                    rotation={[0, Math.PI / 2, 0]}
                >
                    <group
                        position={[0, 0.21, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.49, 1, 0.57]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(
                                nodes.Window_Glass003_1 as Mesh
                            )}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Window_Glass003_1 as Mesh)
                                )
                            )}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(
                                nodes.Window_Glass003_2 as Mesh
                            )}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Window_Glass003_2 as Mesh)
                                )
                            )}
                        />
                    </group>
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={getGeometry(nodes.Window_Frame004 as Mesh)}
                    material={materialBorderGen(
                        toMaterialGeom(
                            getGeometry(nodes.Window_Frame004 as Mesh)
                        )
                    )}
                    position={[0.24, 1.51, -0.53]}
                    rotation={[Math.PI, 0, Math.PI]}
                >
                    <group
                        position={[0, 0.21, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.49, 1, 0.57]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(
                                nodes.Window_Glass004_1 as Mesh
                            )}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Window_Glass004_1 as Mesh)
                                )
                            )}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(
                                nodes.Window_Glass004_2 as Mesh
                            )}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Window_Glass004_1 as Mesh)
                                )
                            )}
                        />
                    </group>
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={getGeometry(nodes.Window_Frame005 as Mesh)}
                    material={materialBorderGen(
                        toMaterialGeom(
                            getGeometry(nodes.Window_Frame005 as Mesh)
                        )
                    )}
                    position={[-0.24, 1.51, -0.53]}
                    rotation={[Math.PI, 0, Math.PI]}
                >
                    <group
                        position={[0, 0.21, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.49, 1, 0.57]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(
                                nodes.Window_Glass005_1 as Mesh
                            )}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Window_Glass004_1 as Mesh)
                                )
                            )}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(
                                nodes.Window_Glass005_2 as Mesh
                            )}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Window_Glass004_1 as Mesh)
                                )
                            )}
                        />
                    </group>
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={getGeometry(nodes.Window_Frame006 as Mesh)}
                    material={materialBorderGen(
                        toMaterialGeom(
                            getGeometry(nodes.Window_Frame006 as Mesh)
                        )
                    )}
                    position={[-0.53, 1.51, -0.24]}
                    rotation={[0, -1.57, 0]}
                >
                    <group
                        position={[0, 0.21, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.49, 1, 0.57]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(
                                nodes.Window_Glass006_1 as Mesh
                            )}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Window_Glass006_1 as Mesh)
                                )
                            )}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(
                                nodes.Window_Glass006_2 as Mesh
                            )}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Window_Glass006_1 as Mesh)
                                )
                            )}
                        />
                    </group>
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={getGeometry(nodes.Window_Frame007 as Mesh)}
                    material={materialBorderGen(
                        toMaterialGeom(
                            getGeometry(nodes.Window_Frame007 as Mesh)
                        )
                    )}
                    position={[-0.53, 1.51, 0.24]}
                    rotation={[0, -1.57, 0]}
                >
                    <group
                        position={[0, 0.21, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.49, 1, 0.57]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(
                                nodes.Window_Glass007_1 as Mesh
                            )}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Window_Glass006_1 as Mesh)
                                )
                            )}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(
                                nodes.Window_Glass007_2 as Mesh
                            )}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Window_Glass006_1 as Mesh)
                                )
                            )}
                        />
                    </group>
                </mesh>
                <group position={[-0.46, 1, 0.53]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Ceiling_1 as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(getGeometry(nodes.Ceiling_1 as Mesh))
                        )}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Ceiling_2 as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(getGeometry(nodes.Ceiling_2 as Mesh))
                        )}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Signs_1 as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(getGeometry(nodes.Signs_1 as Mesh))
                        )}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Signs_2 as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(getGeometry(nodes.Signs_2 as Mesh))
                        )}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Signs_3 as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(getGeometry(nodes.Signs_3 as Mesh))
                        )}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Door_Top_Trim as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(
                                getGeometry(nodes.Door_Top_Trim as Mesh)
                            )
                        )}
                    />
                </group>
                <group position={[-0.48, 1, 0.53]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Door_Left_1 as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(
                                getGeometry(nodes.Door_Left_1 as Mesh)
                            )
                        )}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Door_Left_2 as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(
                                getGeometry(nodes.Door_Left_2 as Mesh)
                            )
                        )}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Window_Frame001 as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(
                                getGeometry(nodes.Window_Frame001 as Mesh)
                            )
                        )}
                        position={[0.22, 0.51, 0]}
                    >
                        <group
                            position={[0, 0.21, 0]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={[0.49, 1, 0.57]}
                        >
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={getGeometry(
                                    nodes.Window_Glass001_1 as Mesh
                                )}
                                material={materialBorderGen(
                                    toMaterialGeom(
                                        getGeometry(
                                            nodes.Window_Glass001_1 as Mesh
                                        )
                                    )
                                )}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={getGeometry(
                                    nodes.Window_Glass001_2 as Mesh
                                )}
                                material={materialBorderGen(
                                    toMaterialGeom(
                                        getGeometry(
                                            nodes.Window_Glass001_2 as Mesh
                                        )
                                    )
                                )}
                            />
                        </group>
                    </mesh>
                    <group
                        position={[0.41, 0, 0.04]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.03}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(nodes.Yale_Lock_1 as Mesh)}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Yale_Lock_1 as Mesh)
                                )
                            )}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(nodes.Yale_Lock_2 as Mesh)}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Yale_Lock_2 as Mesh)
                                )
                            )}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(
                            nodes.Pull_to_Open_Panel_1 as Mesh
                        )}
                        material={materialBorderGen(
                            toMaterialGeom(
                                getGeometry(nodes.Pull_to_Open_Panel_1 as Mesh)
                            )
                        )}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(
                            nodes.Pull_to_Open_Panel_2 as Mesh
                        )}
                        material={materialBorderGen(
                            toMaterialGeom(
                                getGeometry(nodes.Pull_to_Open_Panel_2 as Mesh)
                            )
                        )}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={getGeometry(nodes.Roof as Mesh)}
                    material={materialBorderGen(
                        toMaterialGeom(getGeometry(nodes.Roof as Mesh))
                    )}
                    position={[0, 2.39, 0]}
                >
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Lamp_Base as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(getGeometry(nodes.Lamp_Base as Mesh))
                        )}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={getGeometry(nodes.Lamp_Bottom as Mesh)}
                            material={materialBorderGen(
                                toMaterialGeom(
                                    getGeometry(nodes.Lamp_Bottom as Mesh)
                                )
                            )}
                            position={[0, 0.12, 0]}
                        >
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={getGeometry(nodes.Lamp_Lens as Mesh)}
                                material={materialBorderGen(
                                    toMaterialGeom(
                                        getGeometry(nodes.Lamp_Lens as Mesh)
                                    )
                                )}
                                position={[0, 0.08, 0]}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={getGeometry(
                                    nodes.Lamp_Struts as Mesh
                                )}
                                material={materialBorderGen(
                                    toMaterialGeom(
                                        getGeometry(nodes.Lamp_Struts as Mesh)
                                    )
                                )}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={getGeometry(nodes.Lamp_Top as Mesh)}
                                material={materialBorderGen(
                                    toMaterialGeom(
                                        getGeometry(nodes.Lamp_Top as Mesh)
                                    )
                                )}
                                position={[0, 0.14, 0]}
                            />
                        </mesh>
                    </mesh>
                </mesh>
                <group position={[0.46, 1, 0.53]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Door_Right_1 as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(
                                getGeometry(nodes.Door_Right_1 as Mesh)
                            )
                        )}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Door_Right_2 as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(
                                getGeometry(nodes.Door_Right_2 as Mesh)
                            )
                        )}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Window_Frame002 as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(
                                getGeometry(nodes.Window_Frame002 as Mesh)
                            )
                        )}
                        position={[-0.22, 0.51, 0]}
                    >
                        <group
                            position={[0, 0.21, 0]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={[0.49, 1, 0.57]}
                        >
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={getGeometry(
                                    nodes.Window_Glass002_1 as Mesh
                                )}
                                material={materialBorderGen(
                                    toMaterialGeom(
                                        getGeometry(
                                            nodes.Window_Glass002_1 as Mesh
                                        )
                                    )
                                )}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={getGeometry(
                                    nodes.Window_Glass002_2 as Mesh
                                )}
                                material={materialBorderGen(
                                    toMaterialGeom(
                                        getGeometry(
                                            nodes.Window_Glass002_2 as Mesh
                                        )
                                    )
                                )}
                            />
                        </group>
                    </mesh>
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={getGeometry(nodes.Pillars as Mesh)}
                    material={materialBorderGen(
                        toMaterialGeom(getGeometry(nodes.Pillars as Mesh))
                    )}
                    position={[-0.56, 0, 0.56]}
                    rotation={[0, 1.57, 0]}
                />
                <group position={[0.53, 1, -0.46]} rotation={[0, 1.57, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Walls_1 as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(getGeometry(nodes.Walls_1 as Mesh))
                        )}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Walls_2 as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(getGeometry(nodes.Walls_2 as Mesh))
                        )}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={getGeometry(nodes.Wall_Trim as Mesh)}
                        material={materialBorderGen(
                            toMaterialGeom(getGeometry(nodes.Wall_Trim as Mesh))
                        )}
                        position={[-0.46, -1, 0.04]}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('https://s3.amazonaws.com/tardis.digital/TARDIS.glb');
