apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-api
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: martin
spec:
  replicas: 3
