# This file contains secret templates
# Actual secrets are created by the install.sh script
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: geo-dashboard
type: Opaque
data:
  # These will be populated by install.sh
  # POSTGRES_USER: base64_encoded_value
  # POSTGRES_PASSWORD: base64_encoded_value  
  # POSTGRES_DBNAME: base64_encoded_value
---
apiVersion: v1
kind: Secret
metadata:
  name: core-secrets
  namespace: geo-dashboard
type: Opaque
data:
  # These will be populated by install.sh
  # DJANGO_SECRET_KEY: base64_encoded_value 