---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app.kubernetes.io/name: postgres-secrets
    app.kubernetes.io/part-of: maps-platform
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DBNAME: "${POSTGRES_DBNAME}"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  labels:
    app.kubernetes.io/name: keycloak-secrets
    app.kubernetes.io/part-of: maps-platform
    app.kubernetes.io/component: auth
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
  KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
  POSTGRES_USER: "${KC_POSTGRES_USER}"
  POSTGRES_PASSWORD: "${KC_POSTGRES_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  labels:
    app.kubernetes.io/name: redis-secrets
    app.kubernetes.io/part-of: maps-platform
    app.kubernetes.io/component: cache
type: Opaque
stringData:
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    app.kubernetes.io/name: api-secrets
    app.kubernetes.io/part-of: maps-platform
    app.kubernetes.io/component: api
type: Opaque
stringData:
  SECRET_KEY: "${SECRET_KEY}"
  DATABASE_URL: "${DATABASE_URL}"
  REDIS_URL: "${REDIS_URL}"
