# Generated by Django 4.1.7 on 2023-04-03 20:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=50, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('metadata', models.JSONField()),
                ('geometry_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Geometries',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('attritutes', models.JSONField()),
                ('style', models.JSONField()),
                ('geometries', models.ManyToManyField(blank=True, to='core.geometry')),
            ],
            options={
                'verbose_name_plural': 'Layers',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('project_type', models.CharField(max_length=50)),
                ('attritutes', models.JSONField()),
                ('layers', models.ManyToManyField(blank=True, to='core.layer')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('source_type', models.CharField(max_length=50)),
                ('attritutes', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.AddField(
            model_name='layer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.source'),
        ),
        migrations.AddField(
            model_name='geometry',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.source'),
        ),
    ]
