# Generated by Django 4.1.7 on 2023-04-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_geometry_layer_project_source_delete_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='attritutes',
        ),
    ]
