# Generated by Django 4.1.7 on 2023-04-03 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_project_attritutes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geometry",
            name="gid",
        ),
    ]
