# Generated by Django 4.1.7 on 2023-04-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_geometry_id_geometry_gid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geometry",
            name="gid",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
