# Generated by Django 4.1.7 on 2023-04-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_geometry_gid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geometry",
            name="gid",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
