# Generated by Django 4.1.7 on 2023-05-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_geometry_gid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geometry",
            name="gid",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
