# Generated by Django 4.2.2 on 2023-06-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_attritutes_source_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometry',
            name='gid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
